site_name: Pillar
site_url: https://100nandoo.github.io/Pillar/screen/
repo_url: https://github.com/100nandoo/Pillar
theme:
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
  font:
    text: Noto Sans
    code: Fira Mono
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  palette:
    - scheme: slate
      primary: pink
      accent: indigo
      toggle:
        icon: material/brightness-4 
        name: Switch to light mode
    - scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  

nav:
  - 'Overview': index.md
  - 'Screen': screen.md
  - 'Changelog': CHANGELOG.md
  - 'API': api/api.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format