[versions]
kotlin = "1.6.10"
ktlint = "0.43.2"
detekt = "1.20.0-RC1"
dokka = "1.6.10"
junit = "4.13.2"

compile_sdk_version = "31"
min_sdk_version = "21"
target_sdk_version = "31"

espresso_core = "3.4.0"
androidx_test_ext = "1.1.3"
androidx_test = "1.4.0"

appcompat = "1.4.1"
annotation = "1.3.0"
constraint_layout = "2.1.2"
core_ktx = "1.7.0"

retrofit = "2.9.0"
retrofit_converter = "0.8.0"

hilt = "2.41"

[libraries]
junit = { module = "junit:junit", version.ref = "junit" }

androidx_appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx_annotation = { module = "androidx.annotation:annotation", version.ref = "annotation"}
androidx_constraint_layout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraint.layout" }
androidx_core_ktx = { module = "androidx.core:core-ktx", version.ref = "core.ktx" }

androidx_test_rules = { module = "androidx.test:rules", version.ref = "androidx.test" }
androidx_test_runner = { module = "androidx.test:runner", version.ref = "androidx.test" }
androidx_test_ext_junit = { module = "androidx.test.ext:junit", version.ref = "androidx.test.ext" }
androidx_test_ext_junit_ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx.test.ext" }

espresso_core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso.core" }
agp = { module = "com.android.tools.build:gradle", version = "7.1.2" }
kgp = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
dokka_gradle_plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
dokka_core = { module = "org.jetbrains.dokka:dokka-core", version.ref = "dokka" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit_converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit_converter" }

kotlinx_json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.3.2" }

hilt_android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt_compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt_gradle_plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "10.2.1" }
versions = { id = "com.github.ben-manes.versions", version = "0.42.0" }
